version: '3.8'
services:
  pyload:
    build: .
    container_name: oasislab-file-uploader
    ports:
      - "5005:5005"
    volumes:
      - /home/steven/jellyfin/media:/app/downloads
    restart: unless-stopped
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    command: gunicorn --bind 0.0.0.0:5005 app:app
