version: '3.8'
services:
  pyload:
    build: .
    container_name: jellyfin-file-uploader
    ports:
      - "5005:5005"
    volumes:
      # Point towards the folder structure where you want to store the downloaded files (likely your Jellyfin library)
      - /downloads:/app/downloads
    restart: unless-stopped
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    command: gunicorn --bind 0.0.0.0:5005 app:app
